Repository precice/micro-manager, pull requests merged in 2024-07, with the labels that each got.

#114 Move micro_dt from coupling parameters to simulation parameters in the configuration
  CHANGELOG.md
  examples/micro-manager-cpp-adaptivity-config.json
  examples/micro-manager-cpp-config.json
  examples/micro-manager-python-adaptivity-config.json
  examples/micro-manager-python-config.json
  micro_manager/config.py
  tests/integration/test_unit_cube/micro-manager-config-global-adaptivity-parallel.json
  tests/integration/test_unit_cube/micro-manager-config-global-adaptivity.json
  tests/integration/test_unit_cube/micro-manager-config-local-adaptivity.json
  tests/integration/test_unit_cube/micro-manager-config-parallel-1.json
  tests/integration/test_unit_cube/micro-manager-config-parallel-2.json
  tests/unit/micro-manager-config.json
  tests/unit/micro-manager-config_crash.json
Labels: breaking change

#113 Make interpolation after crash optional
  .github/workflows/run-unit-tests.yml
  CHANGELOG.md
  docs/configuration.md
  docs/installation.md
  docs/running.md
  micro_manager/config.py
  micro_manager/micro_manager.py
  pyproject.toml
  tests/unit/micro-manager-config_crash.json
  tests/unit/test_interpolation.py
  tests/unit/test_micro_simulation_crash_handling.py
Labels: enhancement

#101 Snapshot computation
  .github/workflows/run-unit-tests.yml
  CHANGELOG.md
  examples/clean-example.sh
  examples/parameter.hdf5
  examples/snapshot-config.json
  examples/snapshot_postprocessing.py
  micro_manager/__init__.py
  micro_manager/config.py
  micro_manager/micro_manager.py
  micro_manager/micro_manager_base.py
  micro_manager/snapshot/__init__.py
  micro_manager/snapshot/dataset.py
  micro_manager/snapshot/snapshot.py
  pyproject.toml
  tests/unit/.gitignore
  tests/unit/hdf_files/test_parameter.hdf5
  tests/unit/snapshot-config.json
  tests/unit/test_hdf5_functionality.py
  tests/unit/test_micro_manager.py
  tests/unit/test_parameter.hdf5
  tests/unit/test_snapshot_computation.py
Labels: new-feature

#118 Explicitly check if the time window has completed
  CHANGELOG.md
  micro_manager/micro_manager.py
Labels: bug
