Repository precice/micro-manager, pull requests merged in 2025-04, with the labels that each got.

#152 Remove export of adaptivity CPU time
  CHANGELOG.md
  micro_manager/adaptivity/global_adaptivity.py
  micro_manager/adaptivity/local_adaptivity.py
  micro_manager/micro_manager.py
  tests/unit/test_micro_manager.py
  tests/unit/test_micro_simulation_crash_handling.py
Labels: bug

#153 Refactor logging wrapper commands to have more sensible names
  CHANGELOG.md
  micro_manager/adaptivity/adaptivity.py
  micro_manager/adaptivity/global_adaptivity.py
  micro_manager/adaptivity/local_adaptivity.py
  micro_manager/config.py
  micro_manager/micro_manager.py
  micro_manager/snapshot/snapshot.py
  micro_manager/tools/logging_wrapper.py
Labels: enhancement

#117 Add option for lazy creation of micro simulations
  CHANGELOG.md
  docs/configuration.md
  micro_manager/adaptivity/adaptivity.py
  micro_manager/adaptivity/global_adaptivity.py
  micro_manager/adaptivity/local_adaptivity.py
  micro_manager/config.py
  micro_manager/interpolation.py
  micro_manager/micro_manager.py
Labels: new-feature

#161 Checkpoint lazily created simulation only if a checkpoint is necessary
  CHANGELOG.md
  micro_manager/micro_manager.py
Labels: bug

#160 Fix adaptivity metrics logging and add logging documentation
  CHANGELOG.md
  docs/configuration.md
  docs/logging.md
  micro_manager/adaptivity/adaptivity.py
  micro_manager/adaptivity/global_adaptivity.py
  micro_manager/adaptivity/local_adaptivity.py
  micro_manager/micro_manager.py
Labels: bug
